### ISSUE TITLE
Validation errors for ResponseThread

### ISSUE THREAD

**Issue by Layerex** [uburuntu/api2ch#1]
Error when trying to request thread:
```
pydantic.error_wrappers.ValidationError: 2 validation errors for ResponseThread
advert_mobile_image
  field required (type=value_error.missing)
advert_mobile_link
  field required (type=value_error.missing)
```

**Comment by uburuntu** [comment]
Thanks for reporting!

The `advert_mobile_image` and `advert_mobile_link` fields sometimes seem to be missing, despite the scheme — I marked them as Optional. The problem should disappear with version  `v1.2.0`.

Don't forget to update: `pip install api2ch -U`
